baseurl = "/"
languageCode = "en-us"
title = "giftwrap"
theme = "terminal"
pagination.pagerSize = 10

[markup.goldmark.extensions]
  definitionList = true

[markup.highlight]
noClasses = false

[params]
  contentTypeName = "docs"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  themeColor = "green"
  showLanguageSelector = false
  subtitle = "Wrap your go packages with a gentle kiss."
  showLastUpdated = true 
  updateDatePrefix = "last update:"
  Toc = true 
  owner = "indrora"
  

[params.logo]
  logoText = "giftwrap"
  logoHomeLink = "/"

[[menu.main]]
  identifier = "quickstart"
  name = "Quickstart"
  url = "/docs/quickstart/"
  weight = 1

[[menu.main]]
  identifier = "wrapfile"
  name = "Wrapfile"
  url = "/docs/wrapfile/"
  weight = 2

[[menu.main]]
  identifier = "cli"
  name = "CLI"
  url = "/docs/cli/"
  weight = 3

