name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches-ignore:
      - "*"
  workflow_dispatch:

permissions:
  contents: write
  statuses: read

defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repo
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          token: ${{github.token}}
      - name: Eat the dogfood.
        run: go run . release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          working_directory: _dist
          files: |
            *.zip
            *.tar.gz
